#!/bin/bash

set -eux

./reformat

# is git installed and on the $PATH?
echo $PATH
git help &> /dev/null

if [[ -n $(git diff --stat) ]]; then
    echo "Repo state dirty after ./reformat:"
    git diff --stat

    exit 1
fi
